#  ██▀███   ▒█████   ▒█████   ███▄ ▄███▓  ██████  ██▓███   ██▒   █▓ ██▓███
# ▓██ ▒ ██▒▒██▒  ██▒▒██▒  ██▒▓██▒▀█▀ ██▒▒██    ▒ ▓██░  ██▒▓██░   █▒▓██░  ██▒
# ▓██ ░▄█ ▒▒██░  ██▒▒██░  ██▒▓██    ▓██░░ ▓██▄   ▓██░ ██▓▒ ▓██  █▒░▓██░ ██▓▒
# ▒██▀▀█▄  ▒██   ██░▒██   ██░▒██    ▒██   ▒   ██▒▒██▄█▓▒ ▒  ▒██ █░░▒██▄█▓▒ ▒
# ░██▓ ▒██▒░ ████▓▒░░ ████▓▒░▒██▒   ░██▒▒██████▒▒▒██▒ ░  ░   ▒▀█░  ▒██▒ ░  ░
# ░ ▒▓ ░▒▓░░ ▒░▒░▒░ ░ ▒░▒░▒░ ░ ▒░   ░  ░▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░   ░ ▐░  ▒▓▒░ ░  ░
#   ░▒ ░ ▒░  ░ ▒ ▒░   ░ ▒ ▒░ ░  ░      ░░ ░▒  ░ ░░▒ ░        ░ ░░  ░▒ ░
#   ░░   ░ ░ ░ ░ ▒  ░ ░ ░ ▒  ░      ░   ░  ░  ░  ░░            ░░  ░░
#    ░         ░ ░      ░ ░         ░         ░                 ░
#                                                             ░
# Configuration RoomsPvP |
#

general:
  # Control the maximum number of rooms a player can create
  total-rooms: 75
  # World to store all rooms in
  world-name: "world"
